##register
POST http://localhost:3000/register
Content-Type: application/json

{
    "name" : "yogesh",
    "email" : "yogesshrutil@gmail.com",
    "password": "yogesh"
}

###login

POST http://localhost:3000/login
Content-Type: application/json

{
    "email" : "user@gmail.com",
    "password": "user"
}
